spring.datasource.url=jdbc:mysql://localhost:3306/intelligence
spring.datasource.username=root
spring.datasource.password=Akhil@04

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect